# Generated by Django 2.2.3 on 2019-07-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('phrase', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveIntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='google_scraper.Query')),
            ],
            options={
                'ordering': ('-position',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='google_scraper.Query')),
            ],
            options={
                'ordering': ('-position',),
            },
        ),
    ]
