# Generated by Django 2.2.3 on 2019-07-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_scraper', '0002_auto_20190719_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularWord',
        ),
    ]
