# Generated by Django 2.2.3 on 2019-07-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_scraper', '0004_query_num_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('position',)},
        ),
    ]
